### ISSUE TITLE
ibm_boto3 is not exists in Conda repositories

### ISSUE THREAD

**Issue by gilv** [IBM/ibm-cos-sdk-python#3]
Tried to install ibm_boto3 with conda.

Got:

PackagesNotFoundError: The following packages are not available from current channels:

  - ibm_boto3

Current channels:

  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch

**Comment by cpcunningham** [comment]
Hi @gilv - 
We need some more detail to be able to assist you.
Can you detail the steps you are taking and any error details.

**Comment by cpcunningham** [comment]
Hi @gilv - The boto3  you can instlall is the amazon version.
The ibm version of the sdks are not in the conda archives.
Use pip to instlall
 pip  install ibm-cos-sdk
You will still be able to see the instlaled packages via conda
conda list

**Comment by gilv** [comment]
I am using Conda to install packages with Conda. I understand how to install with pip, but Conda is separate project and it creates environment by itself. 
Since conda can perfectly install boto3, it suppose also perfectly install ibm_boto3. 
All you need is to update Conda repositories

**Comment by cpcunningham** [comment]
@gilv  on Conda - We will refer this to the Offerings Manager and will let you know the outcome..

**Comment by smcgrath-IBM** [comment]
There is no current plan to support the Conda repositories, but could be included in future..

**Comment by fe01134** [comment]
This would be useful to have so that I can run my Watson Studio Juptyer notebooks locally before I deploy them to the cloud.  I would like to still reference the Object storage to get access to the data.    This is really important to have a standalone local development environment to make it faster and more efficient to develop Jupyter notebooks before publishing them to Watson Studio.  Can you please suggest work arounds?

I setup virtual env and then installed:
pip install awscli
pip install pandas
**Code**

`def __iter__(self): return 0
@hidden_cell
!The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
!You might want to remove those credentials before you share your notebook.
client_d552ed0e5f3545b59faefcef9ef01a22 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='my key',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')
body = client_d55.get_object(Bucket='apmmaintenance-donotdelete-pr-sussitoyzlhzur',Key='HistoricalQuotes.csv')['Body']
! add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )
dateparse = lambda dates: pd.datetime.strptime(dates, '%m/%d/%y')
data = pd.read_csv(body, parse_dates=['date'], index_col='date',date_parser=dateparse)
data.head()`

**Error**
---> 18 body = client_d55.get_object(Bucket='apmmaintenance-donotdelete-pr-sussitoyzlhzur',Key='HistoricalQuotes.csv')['Body']
     19 # add missing __iter__ method, so pandas accepts body as file-like object

**Comment by aa7955** [comment]
@fe01134 So, you're installing it wrong that's why. You're not supposed to install `awscli` since this is not an AWS product. You have to use `ibm_boto3` and install that with `pip install ibm-cos-sdk`.

**Comment by Shiven004** [comment]
Thanks!!!!  pip install ibm-cos-sdk workded for me!!!
